#! /bin/sh
### BEGIN INIT INFO
# Provides:          eye-control
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: eye-control
# Description:       Eye control for moving the camera
### END INIT INFO


