#! /bin/sh
### BEGIN INIT INFO
# Provides:          rpi-cam-forward
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: rpi-cam-forward
# Description:       Rpi Cam forward to dummy video device
### END INIT INFO

# This is needed in order to be able to "see" the video from the rpi cam from the browser.
